nfsServer: "172.16.0.9"

db:
  resources: {"requests": {"cpu": "25m", "memory": "512Mi"}, "limits": {"memory": "1Gi"}}
  nfsPath: "/srm/etl-staging/db"

elasticsearch:
  resources: {"requests": {"cpu": "50m", "memory": "2Gi"}, "limits": {"memory": "4Gi"}}
  nfsPath: "/srm/etl-staging/elasticsearch"
  secretName: "elasticsearch"
  ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
  image: ghcr.io/whiletrue-industries/srm-etl-elasticsearch:c1f1974c43f9a4113bc0c644e9e8047c5abf563a@sha256:0cca88e7ae514e170d57319e378fd03ce8c3aa063ab99593c581f0c863b1b0ff


kibana:
  resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"memory": "512Mi"}}

api:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "1Gi"}}
  ES_INDEX_NAME: "srm"
  ES_DATAPACKAGE: |
    https://srm-staging.datacity.org.il/dataset/d3e2603d-fd87-42a9-ab5b-ff15e22013f8/resource/48aba26d-eef2-4720-a2d2-c26d8377a8cb/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/0386f511-bd1b-4931-8c3c-88c45272f642/resource/964e3928-c8c1-4460-a5c2-0f46f18c7ab5/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/71a7e998-4984-472a-9e96-66890bbef5f5/resource/680bd503-7e7b-4674-878b-4635690bb099/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/657a1b09-2474-4309-aac8-381d41e115d8/resource/da753aa2-f5e0-43f0-a6de-65f6219d9421/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/8057b3a6-3c0f-4630-b3fa-2b2a8de93d27/resource/8bed510b-4889-4792-bb9d-d6f35cf6db83/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/4faa5ef4-2d66-4e4d-8aa9-f72c53f02a2f/resource/0fbd4381-ef19-4025-80b6-069ebc6f9955/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/8057b3a6-3c0f-4630-b3fa-2b2a8de93d27/resource/8bed510b-4889-4792-bb9d-d6f35cf6db83/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/cef289db-5053-4cb5-abcb-180a3ff8d36e/resource/9c102bae-d526-4eab-b210-e8bd3ae2d3db/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/78a1c665-1c91-423c-925e-889693659e51/resource/63fd9602-2eed-4c9b-bbbf-8a6bdcfabda1/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/c9e7f03f-c182-4b3a-baab-3af966ffad92/resource/04267d24-f2a9-4241-a304-b155776349ed/download/datapackage.json

minio:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}
  nfsPath: "/srm/etl-staging/minio"

etl:
  resources: {"requests": {"cpu": "247m", "memory": "1953Mi"}}
  EXTERNAL_ADDRESS: "https://srm-staging-etl.whiletrue.industries"
  secretName: "etl"
  ckanHost: "https://srm-staging.datacity.org.il"
  envName: "staging"
  mapboxTilesetId: "srm-kolzchut.point-data-staging"
  mapboxTilesetName: "SRM Geo Staging Data"
  mapboxTilesetInaccurateId: "srm-kolzchut.point-data-inaccurate-staging"
  mapboxTilesetInaccurateName: "SRM Geo Staging Data Inaccurate"

ingresses:
  - name: etl
    rules:
      - host: srm-staging-etl.whiletrue.industries
        serviceName: etl
        servicePort: 5000
  - name: api
    rules:
      - host: srm-staging-api.whiletrue.industries
        serviceName: api
        servicePort: 5000
  - name: kibana
    rules:
      - host: srm-staging-kibana.whiletrue.industries
        serviceName: kibana
        servicePort: 5601
  - name: elasticsearch
    rules:
      - host: srm-staging-elasticsearch.whiletrue.industries
        serviceName: elasticsearch
        servicePort: 9200

vertical_pod_autoscalers:
  - apiVersion: apps/v1
    kind: deployment
    name: api
  - apiVersion: apps/v1
    kind: deployment
    name: db
  - apiVersion: apps/v1
    kind: deployment
    name: elasticsearch
  - apiVersion: apps/v1
    kind: deployment
    name: etl
  - apiVersion: apps/v1
    kind: deployment
    name: kibana
  - apiVersion: apps/v1
    kind: deployment
    name: minio
