nfsServer: "172.16.0.9"

db:
  resources: {"requests": {"cpu": "25m", "memory": "512Mi"}, "limits": {"memory": "1Gi"}}
  nfsPath: "/srm/etl-production/db"
  backup:
    enabled: true

elasticsearch:
  resources: {"requests": {"cpu": "50m", "memory": "2Gi"}, "limits": {"memory": "4Gi"}}
  nfsPath: "/srm/etl-production/elasticsearch"
  secretName: "elasticsearch"
  ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
  enableBackups: true

kibana:
  resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"memory": "512Mi"}}

api:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "1Gi"}}
  ES_INDEX_NAME: "srm"
  ES_DATAPACKAGE: |
    https://srm.datacity.org.il/dataset/5423f041-47f3-4325-a116-8ae56c317d79/resource/d4dcb112-fcc9-4ea7-988d-e0819c4c79c3/download/datapackage.json
    https://srm.datacity.org.il/dataset/812345ae-521e-4171-9a91-d66d0fcf03df/resource/c23e5c4f-078d-45b9-bc9c-356ed87c4028/download/datapackage.json
    https://srm.datacity.org.il/dataset/c5dd1e15-4be8-4eb8-b54e-28cab16fcd5e/resource/15112d71-3a67-42cb-bbbd-6fb316173e3b/download/datapackage.json
    https://srm.datacity.org.il/dataset/c392c588-2443-4319-91ec-de52f9221f2a/resource/f5c0c259-6062-499f-87d5-492de079baba/download/datapackage.json
    https://srm.datacity.org.il/dataset/6f1a45c6-c855-43c8-8a3f-acaad318581c/resource/b72bd999-4f8c-4259-b145-a4d6d843ba87/download/datapackage.json
    https://srm-staging.datacity.org.il/dataset/0386f511-bd1b-4931-8c3c-88c45272f642/resource/964e3928-c8c1-4460-a5c2-0f46f18c7ab5/download/datapackage.json
    https://srm.datacity.org.il/dataset/f96fbd7d-4b31-4611-a4be-be285e3dfb10/resource/0e0da265-3856-4e2b-85ca-c03bdf47016a/download/datapackage.json

minio:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}
  nfsPath: "/srm/etl-production/minio"
  backup:
    enabled: true
    TARGET_BUCKET_PATH: "kolzchut-backups/srm-etl-minio"

etl:
  resources: {"requests": {"cpu": "247m", "memory": "1953Mi"}, "limits": {"memory": "4000Mi"}}
  EXTERNAL_ADDRESS: "https://srm-production-etl.whiletrue.industries"
  secretName: "etl"
  ckanHost: "https://srm.datacity.org.il"
  envName: "production"
  mapboxTilesetId: "srm-kolzchut.point-data"
  mapboxTilesetName: "SRM Geo Data"
  mapboxTilesetInaccurateId: "srm-kolzchut.point-data-inaccurate"
  mapboxTilesetInaccurateName: "SRM Geo Data Inaccurate"

ingresses:
  - name: etl
    rules:
      - host: srm-production-etl.whiletrue.industries
        serviceName: etl
        servicePort: 5000
  - name: api
    rules:
      - host: api.kolsherut.org.il
        serviceName: api
        servicePort: 5000
  - name: kibana
    rules:
      - host: srm-production-kibana.whiletrue.industries
        serviceName: kibana
        servicePort: 5601
  - name: elasticsearch
    rules:
      - host: srm-production-elasticsearch.whiletrue.industries
        serviceName: elasticsearch
        servicePort: 9200

vertical_pod_autoscalers:
  - apiVersion: apps/v1
    kind: deployment
    name: api
  - apiVersion: apps/v1
    kind: deployment
    name: db
  - apiVersion: apps/v1
    kind: deployment
    name: elasticsearch
  - apiVersion: apps/v1
    kind: deployment
    name: etl
  - apiVersion: apps/v1
    kind: deployment
    name: kibana
  - apiVersion: apps/v1
    kind: deployment
    name: minio
