# nfsServer: ""

db:
  name: db
  image: ghcr.io/whiletrue-industries/srm-etl-db:9ce02bcde3742805847ed5e925fe7da0e01cab34@sha256:ebb25f6a73151e0cf9167e8fb25590b6d3064b4771fdf2a761836c9fdc08ecb3
  resources: {}
  # nfsPath: ""
  backup:
    enabled: false
    name: db-backup
    image: ghcr.io/whiletrue-industries/srm-etl-db:9ce02bcde3742805847ed5e925fe7da0e01cab34@sha256:ebb25f6a73151e0cf9167e8fb25590b6d3064b4771fdf2a761836c9fdc08ecb3
    # every Sunday 2:53
    schedule: "53 2 * * 0"
    resources:
      requests: {"cpu": "25m",  "memory": "200Mi"}
      limits: {"cpu": "165m", "memory": "400Mi"}
  restore:
    enabled: false
    awsAccessKeyId: ""
    awsSecretAccessKey: ""
    backupBucketPath: ""

elasticsearch:
  name: elasticsearch
  image: ghcr.io/whiletrue-industries/srm-etl-elasticsearch:007057b0436d1ac6a1e20453814249d6a296c1df@sha256:d8e222b8fa5ba41be99aa3c7c621c96195d7b30755c4e95b80fb1a4a11c5b7e2
  resources: {}
  # nfsPath: ""
  # secretName: "elasticsearch"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  enableBackups: false

kibana:
  name: kibana
  image: docker.elastic.co/kibana/kibana:7.13.4@sha256:17d0ec16b8fc31efcc2dff66549d3da13cded0c9be66d240d19f2515f611bf7a
  resources: {}

api:
  name: api
  image: ghcr.io/whiletrue-industries/srm-api:latest
  resources: {}
  ES_INDEX_NAME: "srm"
  ES_DATAPACKAGE: "https://next.obudget.org/datapackages/budgetkey/gov_decisions/datapackage.json"

# minio is only deployed if etl.S3_ENDPOINT is not defined
minio:
  name: minio
  image: minio/minio:edge@sha256:78b6513160ee72794698b808afbeff67b44b510d6d024e0728adc57d726b6c8b
  resources: {}
  backup:
    enabled: false
    name: minio-backup
    image: ghcr.io/whiletrue-industries/srm-devops-aws-s3-backup@sha256:fd44f4c0540dd68d0d154e39f5b70a7ed767414943881b7bab5298656cdfd964
    # every Sunday 2:13
    schedule: "13 2 * * 0"
    TARGET_BUCKET_PATH: ""
    resources:
      requests: { "cpu": "25m",  "memory": "200Mi" }
      limits: { "cpu": "165m", "memory": "400Mi" }

etl:
  name: etl
  image: ghcr.io/whiletrue-industries/srm-etl:latest
  resources: {}
  EXTERNAL_ADDRESS: "http://localhost:15000"
  secretName: "etl"
  # S3SecretName: "etl-s3"

ingresses: []
vertical_pod_autoscalers: []
